[package]
name = "rate-limiter"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono="0.4"
tokio={ version = "1", features = ["full"] }
futures="0.3.5"
dashmap="6.1.0"
axum = "0.8.6"
serde = "1.0.228"
